[build]
  functions = ".netlify/functions"
  # ИСПРАВЛЕНО: Указываем корневой каталог, где лежит index.html и JS
  publish = "."

# Правило перенаправления
[[redirects]]
  # ИСПРАВЛЕНО: Меняем from на внешний путь /functions/*.
  # Теперь в chat.js вы можете использовать PROXY_URL = "/functions/gemini-proxy"
  from = "/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200