[build]
  functions = ".netlify/functions"
  # Указываем несуществующую папку, чтобы Netlify не искал статику
  publish = "public-placeholder" 

# Правило перенаправления
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200